# Generated by Django 2.2.4 on 2019-08-03 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='self_introduce',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
