# Generated by Django 2.2.4 on 2019-08-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='profile_imgs/'),
        ),
    ]
