# Generated by Django 2.1.8 on 2019-08-09 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(max_length=200)),
                ('pub_date', models.DateField(null=True)),
                ('confirmation', models.FileField(null=True, upload_to='')),
                ('rent_term', models.CharField(choices=[('장기(2주이상)', '장기(2주이상)'), ('단기(2주미만)', '단기(2주미만)')], max_length=128)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('price', models.CharField(max_length=200)),
                ('floor', models.CharField(max_length=200)),
                ('room_type', models.CharField(choices=[('원룸', '원룸'), ('투룸', '투룸'), ('복층형 원룸', '복층형 원룸'), ('쓰리룸+', '쓰리룸+')], max_length=128)),
                ('area', models.CharField(max_length=200)),
                ('host_stuff', models.CharField(choices=[('있음', '있음'), ('없음', '없음')], max_length=128)),
                ('parking', models.CharField(choices=[('있음', '있음'), ('없음', '없음')], max_length=128)),
                ('pet', models.CharField(choices=[('가능', '가능'), ('불가능', '불가능')], max_length=128, null=True)),
                ('elevator', models.CharField(choices=[('있음', '있음'), ('없음', '없음')], max_length=128, null=True)),
                ('aircon', models.CharField(choices=[('있음', '있음'), ('없음', '없음')], max_length=128, null=True)),
                ('fridge', models.CharField(choices=[('있음', '있음'), ('없음', '없음')], max_length=128, null=True)),
                ('washingmachine', models.CharField(choices=[('있음', '있음'), ('없음', '없음')], max_length=128, null=True)),
                ('desk', models.CharField(choices=[('있음', '있음'), ('없음', '없음')], max_length=128, null=True)),
                ('bed', models.CharField(choices=[('있음', '있음'), ('없음', '없음')], max_length=128, null=True)),
                ('sink', models.CharField(choices=[('있음', '있음'), ('없음', '없음')], max_length=128, null=True)),
                ('detail', models.TextField()),
                ('main_img', models.ImageField(null=True, upload_to='')),
                ('other_img', models.ImageField(null=True, upload_to='')),
                ('room_img', models.ImageField(null=True, upload_to='')),
                ('address1', models.CharField(max_length=128, null=True)),
                ('address2', models.CharField(max_length=128, null=True)),
                ('address3', models.CharField(max_length=128, null=True)),
                ('address4', models.CharField(max_length=128, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(through='bangregister.Like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangregister.Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangregister.Room'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangregister.Room'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
