# Generated by Django 2.1.8 on 2019-07-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangregister', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('confirmation', models.FileField(null=True, upload_to='')),
                ('rent_term', models.CharField(choices=[('long_rent', '장기(2주이상)'), ('short_rent', '단기(2주미만)')], max_length=128)),
                ('rent_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.CharField(max_length=200)),
                ('floor', models.CharField(max_length=200)),
                ('room_type', models.CharField(choices=[('one_room', '원룸'), ('two_room', '투룸'), ('two_storied_one', '복층형 원룸'), ('morethan_three', '쓰리룸+')], max_length=128)),
                ('area', models.CharField(max_length=200)),
                ('host_stuff', models.CharField(choices=[('yes', '있음'), ('no', '없음')], max_length=128)),
                ('parking', models.CharField(choices=[('yes', '있음'), ('no', '없음')], max_length=128)),
                ('pet', models.CharField(choices=[('yes', '가능'), ('no', '불가능')], max_length=128)),
                ('elevator', models.CharField(choices=[('yes', '있음'), ('no', '없음')], max_length=128)),
                ('option', models.CharField(choices=[('aircon', '에어컨'), ('fridge', '냉장고'), ('washing_machine', '세탁기'), ('desk', '책상'), ('bed', '침대'), ('sink', '싱크대')], max_length=128)),
                ('detail', models.TextField()),
                ('main_img', models.ImageField(upload_to=None)),
                ('other_img', models.ImageField(upload_to=None)),
                ('room_img', models.ImageField(null=True, upload_to=None)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
