# Generated by Django 2.1.8 on 2019-08-09 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bangregister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='option',
            field=models.CharField(choices=[('에어컨', '에어컨'), ('냉장고', '냉장고'), ('["냉장고", "세탁기"]', '["냉장고", "세탁기"]')], max_length=128),
        ),
    ]
