# Generated by Django 2.1.8 on 2019-07-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangregister', '0002_auto_20190722_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='pub_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='rent_date',
            field=models.DateTimeField(),
        ),
    ]
