# Generated by Django 2.1.8 on 2019-08-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangregister', '0002_auto_20190809_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='creator',
        ),
        migrations.AlterField(
            model_name='room',
            name='option',
            field=models.CharField(choices=[('에어컨', '에어컨'), ('냉장고', '냉장고'), ('세탁기', '세탁기'), ('책상', '책상'), ('침대', '침대'), ('침대', '싱크대')], max_length=128),
        ),
    ]
