# Generated by Django 2.1.8 on 2019-07-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangregister', '0003_auto_20190723_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='main_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='other_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
