# Generated by Django 2.1.8 on 2019-08-09 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangregister', '0002_auto_20190809_2252'),
        ('bangregister', '0004_room_creator'),
    ]

    operations = [
    ]
