# Generated by Django 2.1.8 on 2019-07-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangregister', '0004_auto_20190723_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='rent_date',
        ),
        migrations.AddField(
            model_name='room',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='pub_date',
            field=models.DateField(),
        ),
    ]
