# Generated by Django 2.1.8 on 2019-08-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangregister', '0005_merge_20190809_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='option',
        ),
        migrations.AddField(
            model_name='room',
            name='aircon',
            field=models.CharField(choices=[('있음', '있음'), ('없음', '없음')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='bed',
            field=models.CharField(choices=[('있음', '있음'), ('없음', '없음')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='desk',
            field=models.CharField(choices=[('있음', '있음'), ('없음', '없음')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='fridge',
            field=models.CharField(choices=[('있음', '있음'), ('없음', '없음')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='sink',
            field=models.CharField(choices=[('있음', '있음'), ('없음', '없음')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='washingmachine',
            field=models.CharField(choices=[('있음', '있음'), ('없음', '없음')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='elevator',
            field=models.CharField(choices=[('있음', '있음'), ('없음', '없음')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='pet',
            field=models.CharField(choices=[('가능', '가능'), ('불가능', '불가능')], max_length=128, null=True),
        ),
    ]
