# Generated by Django 2.1.8 on 2019-07-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangregister', '0005_auto_20190725_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='pub_date',
            field=models.DateField(null=True),
        ),
    ]
