# Generated by Django 2.1.8 on 2019-08-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangregister', '0006_auto_20190725_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='main_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='other_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
