# Generated by Django 2.1.7 on 2019-08-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangregister', '0006_auto_20190725_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='address1',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='address2',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='address3',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='address4',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
