# Generated by Django 2.2.4 on 2019-08-09 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bangregister', '0007_auto_20190809_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(through='bangregister.Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangregister.Room'),
        ),
        migrations.AddField(
            model_name='like',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangregister.Room'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
