# Generated by Django 2.1.8 on 2019-08-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangregister', '0007_auto_20190801_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='elevator',
            field=models.CharField(choices=[('있음', '있음'), ('없음', '없음')], max_length=128),
        ),
        migrations.AlterField(
            model_name='room',
            name='host_stuff',
            field=models.CharField(choices=[('있음', '있음'), ('없음', '없음')], max_length=128),
        ),
        migrations.AlterField(
            model_name='room',
            name='option',
            field=models.CharField(choices=[('에어컨', '에어컨'), ('냉장고', '냉장고'), ('세탁기', '세탁기'), ('책상', '책상'), ('침대', '침대'), ('침대', '싱크대')], max_length=128),
        ),
        migrations.AlterField(
            model_name='room',
            name='parking',
            field=models.CharField(choices=[('있음', '있음'), ('없음', '없음')], max_length=128),
        ),
        migrations.AlterField(
            model_name='room',
            name='pet',
            field=models.CharField(choices=[('가능', '가능'), ('불가능', '불가능')], max_length=128),
        ),
        migrations.AlterField(
            model_name='room',
            name='rent_term',
            field=models.CharField(choices=[('장기(2주이상)', '장기(2주이상)'), ('단기(2주미만)', '단기(2주미만)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('원룸', '원룸'), ('투룸', '투룸'), ('복층형 원룸', '복층형 원룸'), ('쓰리룸+', '쓰리룸+')], max_length=128),
        ),
    ]
