# Generated by Django 2.2.4 on 2019-08-09 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangregister', '0008_auto_20190809_1745'),
        ('bangregister', '0008_auto_20190809_1640'),
        ('bangregister', '0007_auto_20190809_1704'),
    ]

    operations = [
    ]
