# Generated by Django 2.1.7 on 2019-08-09 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bangregister', '0009_merge_20190809_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangregister.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='main_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='other_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangregister.Room'),
        ),
    ]
